# Generated by Django 5.2.11 on 2026-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_finance_admin',
            field=models.BooleanField(default=False),
        ),
    ]
