# Generated by Django 5.2.11 on 2026-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
