# Generated by Django 5.2.11 on 2026-04-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_alter_lesson_options_alter_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
