# Generated by Django 5.2.11 on 2026-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='subscription',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
